name: Main

on:
  push:
    branches: [main, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    services:
      mysql:
        image: mysql:5.7.31
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todo_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Fixtures loader
        run: bin/console d:m:m --env=test -n && bin/console d:f:l --env=test -n
      
      - name: Run unit test suite
        run: vendor/bin/phpunit --coverage-clover clover.xml